-- TRIGGERS AND EVENTS
-- A TRIGGER IS A BLOCK OF CODE THAT EXECUTES AUTO MATICALLY WHEN AN EVENT TAKES PLACE ON A SPECIFIC TABLE

SELECT *
FROM employee_demographics;

SELECT *
FROM employee_salary;

DELIMITER $$
CREATE TRIGGER employee_insert
	AFTER INSERT ON employee_salary
    FOR EACH ROW
BEGIN
	INSERT INTO employee_demographics (employee_id, first_name, last_name)
    VALUES (NEW.employee_id, NEW.first_name, NEW.last_name);
END $$
DELIMITER ;

-- THIS CODE ABOVE HAS SUCCESSFULLY CREATE THE TRIGGER BUT UNLIKE STORED PROCEDURES
-- YOU CAN NOT SEE IT ON THE LEFT SIDE OF YOUR SCREEN EXCEPT YOU CHECK INSIDE THE EMPLOYEE SALARY TABLE 
-- WHERE YOU WILL FIND THE NEW TRIGGERS
-- N:B YOU CANT ALTER THIS TRIGGER 

INSERT INTO employee_salary (employee_id, first_name, last_name, occupation, salary, dept_id)
VALUES(13, 'Uthman', 'Oduala', 'Analyst', 1000000, NULL)
;

-- IF YOU RUN THE ABOVE CODE, YOU WILL SEE IT HAS ADDED THE 13TH ROW TO YOUR SALARY TABLE AND EACH
-- VALUES WAS INTACT AS SHOWN ABOVE, BUT ON THE DEMOGRAPHICS TABLE, THE ROWS FOR AGE AND OTHERS DID NOT SHOW 
-- CAUSE NOTHING WAS INSERTED THERE.alter

-- EVENTS

 -- AN EVENT IS SIMILAR TO A TRIGGER, A TRIGGER HAPPENS WHEN THE EVENT TAKES PLACE
 -- WHEREAS AN EVENT HAPPENS WHEN IT IS SCHEDULED.
 -- IT IS SUPER HELPFUL FOR AUTOMATION IN GENERAL. 
 
 SELECT *
 FROM employee_demographics;
 
 DELIMITER $$
 CREATE EVENT delete_retiree
 ON SCHEDULE EVERY 30 SECOND
 DO
	BEGIN
		DELETE
        FROM employee_demographics
        WHERE age >= 60;
	END $$
DELIMITER ;
 -- IF YOU RUN THE ABOVE CODE, YOU SEE THAT THE EMPLOYEE ABOVE 60 YEARS ROW HAS BEEN DELETED 
 -- THUS HE HASS BEEN RETIRED. 
 
 